### ISSUE TITLE
Sybil Defender - High January Drop Rates

### ISSUE THREAD

**Issue by rodri-forta** [Epikt1tus/HYDRA#1]
Stablecoin-Depeg-Event-Detection[](https://app.forta.network/bot/0xdbc72013a5a0c7abad1bca19c6ad9d2e2bc00018c7dcdd6e1cc664935cb78b24) had more than 80% of transactions dropped for BSC and Mainnet during January  - Code could have a bug

**Comment by frwd-1** [comment]
If this is an ongoing issue for the Stablecoin-Depeg-Event-Detection bot, please open an issue on that repo
